### ISSUE TITLE
blastn error

### ISSUE THREAD

**Issue by takasoft** [vollbrechtlab/primerDAFT#1]
```
using /mnt/data/my-repo/primerDAFT/primerDAFT/bin/blastn
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    test_run()
  File "test.py", line 32, in test_run
    result = primerDAFT.run(taskData, configFile)
  File "/mnt/data/my-repo/primerDAFT/primerDAFT/__init__.py", line 34, in run
    specResult = specCheck(task, taskResult,configFile)
  File "/mnt/data/my-repo/primerDAFT/primerDAFT/specCheck/specCheck.py", line 102, in specCheck
    stdout, stderr = blast_cline()
  File "/mnt/data/my-repo/primerDAFT/venv/lib/python3.5/site-packages/biopython-1.70-py3.5-linux-x86_64.egg/Bio/Application/__init__.py", line 523, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from "/mnt/data/my-repo/primerDAFT/primerDAFT/bin/blastn -outfmt '6 qseqid qseq qlen qstart qend sseqid sseq sstart send length mismatch evalue' -query 0Y7Cnlt4E37SP2W9_taskResult.json.primer.fa -db fa/Zea_mays.AGPv3.29.dna.genome.fa -evalue 150 -num_threads 8 -task blastn-short", message 'USAGE'
```

**Comment by wkpalan** [comment]
I cannot seem to get the right version. Have you pushed the latest changes. The src folder is still called primer_blast_dx

**Comment by takao42** [comment]
Solved. Change num_threads in the config file to the appropriate number. If your CPU has 4 cores, max num_threads can be 4.
