### ISSUE TITLE
pysam error 

### ISSUE THREAD

**Issue by y9c** [vollbrechtlab/primerDAFT#3]
```bash
Error in getting targets
no sequence/region supplied.
Traceback (most recent call last):
  File "/home/test/.local/share/virtualenvs/primerDAFT-nkDaZfxy/lib/python3.7/site-packages/primerDAFT-0.3.2-py3.7.egg/primerDAFT/specCheck/specCheck.py", line 121, in specCheck
    pot_target_data = get_pot_targets(df_filt,data,task_data,sel_cols,idx_col,pysam_fasta)
  File "/home/test/.local/share/virtualenvs/primerDAFT-nkDaZfxy/lib/python3.7/site-packages/primerDAFT-0.3.2-py3.7.egg/primerDAFT/specCheck/specCheck.py", line 208, in get_pot_targets
    target_dict["left"] = getTargetAttrs(target,"left",x,data,side_cols,target_cols,pysam_fasta)
  File "/home/test/.local/share/virtualenvs/primerDAFT-nkDaZfxy/lib/python3.7/site-packages/primerDAFT-0.3.2-py3.7.egg/primerDAFT/specCheck/getTargetAttrs.py", line 27, in getTargetAttrs
    match_seq = pysam_fasta.fetch(region=region_str)
  File "pysam/libcfaidx.pyx", line 293, in pysam.libcfaidx.FastaFile.fetch
ValueError: no sequence/region supplied.

```

**Comment by wkpalan** [comment]
Can you send me the input sequence or files?

**Comment by wkpalan** [comment]
Closed because no activity
